lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-cayman
defaults:
  - scope: # pour toutes les pages
      path: "" 
      type: "pages"
    values:
      layout: "default"
  - scope: # pour les actualit√©s
      path: "actualites"
      type: "posts"
    values:
      layout: "default"